#!/bin/bash
read -p "Public Key:  " PUBKEY

if [[ ! -d $HOME/.ssh ]]; then
	mkdir $HOME/.ssh
fi

touch $HOME/.ssh/authorized_keys
echo ${PUBKEY} > $HOME/.ssh/authorized_keys
chmod +x master-node-setup
chmod +x node-setup
sudo bash -c "snap install multipass"

# restart bash
echo "Rebooting... After login, execute './3'"
