#!/bin/bash
read -p "Public Key:  " PUBKEY

if [[ ! -d $HOME/.ssh ]]; then
	mkdir $HOME/.ssh
fi

touch $HOME/.ssh/authorized_keys
echo ${PUBKEY} > $HOME/.ssh/authorized_keys
chmod +x master-node-setup
chmod +x node-setup
chmod +x multipass-setup
sudo bash -c "snap install multipass"

# restart bash
exec bash
echo "Please restart the host PC. Then, run './3'"