#!/bin/bash

ipaddrU=$(hostname -I)
ipaddr=${ipaddrU:0:13}
export IPADDR=${ipaddr}
export NODENAME=$(hostname -s)
curl https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml -O
sudo kubeadm init --pod-network-cidr=${ipaddr}/16
sudo kubectl apply -f calico.yaml
