#!/bin/bash

# get IPv4
ipaddrU=$(hostname -I)
ipaddr=${ipaddrU:0:13}
# export env variables
export IPADDR=${ipaddr}
export NODENAME=$(hostname -s)
# error fix; see issue #4581 @ github.com/containerd/containerd
sudo su
rm /etc/containerd/config.toml
systemctl restart containerd
exit
# kubeadm init
sudo kubeadm init --pod-network-cidr=${ipaddr}/16
# cni add-on; using calico
curl https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml -O
kubectl apply -f calico.yaml
# post kubeadm init workflow
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
