#!/bin/bash

# init multipass VMs
multipass launch --name rhizome --cpus 2 --mem 2048M --disk 20GB
multipass launch --name node1 --cpus 2 --mem 3072M --disk 60GB
multipass launch --name node2 --cpus 2 --mem 3072M --disk 60GB
