#!/bin/bash

# init multipass VMs
multipass launch --name rhizome --cpus 2 --mem 2048M --disk 20GB
multipass launch --name node1 --cpus 2 --mem 3072M --disk 60GB
multipass launch --name node2 --cpus 2 --mem 3072M --disk 60GB

# instruction set
echo "You now have three VMs running through Multipass; rhizome, the control plane, node1 & node2, both worker nodes designed for deployments. Here's a quick map of how these VMs will interact within our cluster:"
echo "
Rhizome
^     ^
|     |
Node1 Node2
"
echo "Now, utilize multipass shell <name> for each new VM and run the following command within each VM:"
echo "curl https://raw.githubusercontent.com/samjtro/home-k8s/main/scripts/node-setup >> node-setup; chmod +x node-setup; ./node-setup"
echo "Then, utilize multipass shell rhizome to enter into the rhizome VM (control plane) and enter the following command to start kubernetes with kubeadm init:"
echo "curl https://raw.githubusercontent.com/samjtro/home-k8s/main/scripts/init >> init; chmod +x init; ./init"
echo "After that is done, copy the command given by kubadm pertaining to joining the cluster, and from each worker node run it."
