#!/bin/bash

# docker install
sudo bash -c "apt-get update -y; apt-get upgrade -y; apt-get remove docker docker-engine docker.io containerd runc; apt-get install ca-certificates curl gnupg lsb-release apt-transport-https -y"
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo bash -c "apt-get update -y; apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y"
# k8s install
sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
sudo bash -c "apt-get update -y; apt-get install kubeadm kubelet kubectl -y; apt-mark hold kubelet kubeadm kubectl"
# k8s config
sudo bash -c "swapoff -a; sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab"
# kubectl autocomplete
source /usr/share/bash-completion/bash_completion
echo 'source <(kubectl completion bash)' >> ~/.bashrc; echo 'alias k=kubectl' >> ~/.bashrc; echo 'complete -o default -F __start_kubectl k' >> ~/.bashrc
# restart bash
exec bash
# error fix; see issue #4581 @ github.com/containerd/containerd
sudo su
rm /etc/containerd/config.toml
systemctl restart containerd
exit
