#!/bin/bash

sudo bash -c "sudo apt-get update; sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release"
sudo mkdir -p /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \ 
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \ 
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
# docker & prereqs install & config
sudo bash -c "apt-get update; apt-get install docker.io containerd.io -y"
sudo bash -c "systemctl enable docker; systemctl daemon-reload; systemctl restart docker; usermod -aG docker $USER"
# k8s install
sudo bash -c "apt-get update -y; apt-get install -y apt-transport-https ca-certificates curl"
sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
sudo bash -c "apt-get update -y; sudo apt-get install kubeadm kubelet kubectl -y"
# k8s config
sudo bash -c "swapoff -a; sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab"
# kubectl autocomplete
source /usr/share/bash-completion/bash_completion
echo 'source <(kubectl completion bash)' >>~/.bashrc; echo 'alias k=kubectl' >>~/.bashrc; echo 'complete -o default -F __start_kubectl k' >>~/.bashrc
# restart bash
exec bash
