#!/bin/bash

# docker & prereqs install & config
sudo bash -c "apt-get install docker.io -y; systemctl start docker; systemctl enable docker; usermod -aG docker $USER"
newgrp docker
sudo bash -c "systemctl enable docker; systemctl daemon-reload; systemctl restart docker"
# k8s install
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add
echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
sudo apt-get install kubeadm kubelet kubectl -y
# k8s config
sudo swapoff -a
sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
# kubectl autocomplete
source /usr/share/bash-completion/bash_completion
echo 'source <(kubectl completion bash)' >>~/.bashrc; echo 'alias k=kubectl' >>~/.bashrc; echo 'complete -o default -F __start_kubectl k' >>~/.bashrc
# restart bash
exec bash